apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: pg-backup
  name: pg-backup
  namespace: hasura
spec:
  template:
    metadata:
      labels:
        app: pg-backup
      name: pg-backup
    spec:
      containers:
      - image: hasura/postgres-wal-e:9.6.1-r1
        name: pg-backup
        env:
          - name: PGHOST
            value: "postgres.hasura"
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: postgres.user
                name: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres.password
                name: postgres
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                key: aws.region
                name: hasura-backup
          - name: WALE_S3_PREFIX
            valueFrom:
              configMapKeyRef:
                key: aws.s3.prefix
                name: hasura-backup
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: hasura-backup
                key: aws.access.key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: hasura-backup
                key: aws.secret.access.key
        args:
          - backup
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data
      restartPolicy: Never
      volumes:
        - hostPath:
            path: /home/core/persist/hasura/postgres
          name: data
